version: '3.6'

services:

  users-service:
    build: 
      context: ./users-service
    ports:
     - "8123:8123"
    links:
      - db:db
    depends_on:
     - db
    environment:
     - DATABASE_HOST=db

  db:
    build: ./test-database
